// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ag_anchorinfo;

namespace ag_anchorinfo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200109200148_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ag_anchorinfo.Models.ProspectiveCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AMEmail");

                    b.Property<string>("CustomerNumber");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProspectiveCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
